### ISSUE TITLE
Web.Page

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/hdcharts#2]
69e6d7fae included a large refactor of Web.Page and, along the way, I found https://github.com/athanclark/webpage which has somewhat similar concerns.

@athanclark, if you have the inclination, any thoughts on merging our Web.Page efforts?

Web.Page has a pretty simple premise: think of the various components needed to specify a web page (html, css, js), the various ways to do that (statically, serving, headless html, an svg image instead, libraries linked, js and css split into separate files etc etc), and provide a library to be able to render the page.

So, possible enhancement task:
- split Web.Page components into separate library

**Comment by athanclark** [comment]
I would love to take a look at this, I'll take a more in-depth look later today. My webpage and markup libraries are _supposed_ to work hand-in-hand for this kind of idea (but there is still a lot of clutter and unneccesary compensation lying around it right now) - basically, you organize which components (js, css, html nodes) should be "deployed" similarly; meaning that local assets (something on your local server) should deployed together in the same monad, while hosted assets (on a CDN network or something similar) should be in a different reader monad, supplying their hostname.

Then, once you have all of the markup nodes "deployed" (rendered to a lucid or blaze-html node), you can simply concatenate them together and put it as a parameter to webpage.

I'd also like to make webpage a bit more flexible, too. I've seen some Angular developers placing their `bodyScripts` _after_ the `</body>` tag in their html, for instance. But in general, it should be a bare wrapper skeleton for getting a HTML5 web page together properly.

But, I also haven't touched the project in a few months, so I'll need to catch up :)

**Comment by tonyday567** [comment]
Yep, I can see what you're thinking.  I'm playing around with a lot of different ways of rendering the same webpage "thing" - headless html, css and js served as a separate file, as an svg etc. etc.  And I'm going Ludic exclusively - I'd like to move towards lucid-like libraries for css and js - but that's a long way off.

**Comment by athanclark** [comment]
Same here. I've also got a sass/less compiler on the list of things to cringe about, but _hopefully_, we'll have jquery-like semantic editor combinators for the DOM soon :)

**Comment by tonyday567** [comment]
I split the web page elements out into https://github.com/tonyday567/lucid-page, so will close here.
